testapp/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('cat_question/<int:cat_id>/', views.cat_question, name='cat_question'),
    path('submit-answer/<int:cat_id>/<int:quest_id>/', views.submit_answer, name='submit_answer'),
]

testapp/testapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

testapp/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_reset_done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
]

testapp/main/models.py
from django.contrib.auth.models import User
from django.db import models


class QuizCategory(models.Model):
    """
    Категория тестов
    """
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='images/', default='images/default.png')

    class Meta:
        verbose_name_plural = 'Категории тестов'

    def __str__(self):
        return self.title


class QuestionsCategory(models.Model):
    """
    Вопросы в категориях
    """
    category = models.ForeignKey(QuizCategory, on_delete=models.CASCADE)
    question = models.TextField()
    option_1 = models.CharField(max_length=255)
    option_2 = models.CharField(max_length=255)
    option_3 = models.CharField(max_length=255)
    option_4 = models.CharField(max_length=255)
    level = models.CharField(max_length=100)
    time_limit = models.IntegerField()
    right_option = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return self.question


class UserSubmittedAnswer(models.Model):
    """
    Отправленные пользователем ответы
    """
    question = models.ForeignKey(QuestionsCategory, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    right_answer = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Отправленные пользователем ответы'

testapp/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

testapp/main/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from . import models


@login_required
def index(request):
    """Выводит шаблон главной страницы"""
    catData = models.QuizCategory.objects.all()
    context = {'catData': catData}
    return render(request, 'main/home.html', context)


@login_required
def cat_question(request, cat_id):
    """Вопросы Категории"""
    category = get_object_or_404(models.QuizCategory, id=cat_id)
    question = models.QuestionsCategory.objects.filter(category=category).order_by('id').first()
    context = {'question': question, 'category': category}
    return render(request, 'main/category_question.html', context)


@login_required
def submit_answer(request, cat_id, quest_id):
    """Отправка ответа"""
    if request.method == 'POST':
        category = get_object_or_404(models.QuizCategory, id=cat_id)
        question = models.QuestionsCategory.objects.filter(
            category=category, id__gt=quest_id).exclude(id=quest_id).order_by('id').first()
        quest = models.QuestionsCategory.objects.get(id=quest_id)
        user = request.user
        answer = request.POST['answer']
        models.UserSubmittedAnswer.objects.create(user=user, question=quest, right_answer=answer)
        if question:
            context = {'question': question, 'category': category}
            return render(request, 'main/category_question.html', context)
        else:
            result = models.UserSubmittedAnswer.objects.filter(user=request.user)
            rightAnswer = 0
            percentage = 0
            for row in result:
                if row.question.right_option == row.right_answer:
                    rightAnswer += 1
            percentage = (rightAnswer*100)/result.count()
            context = {'result': result, 'rightAnswer': rightAnswer, 'percentage': percentage}
            return render(request, 'main/result.html', context)
    else:
        return HttpResponse('Метод не разрешен!')

testapp/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

testapp/templates/base.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru">          
  <head> 
    {% include 'includes/head.html' %} 
    <title>{% block title %}Контент{% endblock title %}</title>      
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          Контент не подвезли :(
        {% endblock %} 
      </div>
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 
 

testapp/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© Copyright <span style="color:red">Test</span>App</p>    
</footer>

testapp/templates/includes/head.html
<meta charset="utf-8"> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

testapp/templates/includes/header.html
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'main:home' %}">          
          <span style="color:red">Test</span>App
        </a>                
        {% with request.resolver_match.view_name as view_name %} 
        <ul class="nav nav-pills">          
          {% if user.is_authenticated %}                   
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
        {% endwith %} 
      </div>
    </nav>      
  </header>

testapp/templates/main/category_question.html
{% extends 'base.html' %}
{% block title %}Вопросы Категории {{ category }}{% endblock %}
{% block content %}
    <h2 class="my-4">Вопросы Категории: <span class="text-primary">{{ category }}</span></h2>

    
    <div class="card my-4"> 
        <h4 class="card-header">{{ question.question }}</h4> 
        <form method="post" action="{% url 'main:submit_answer' category.id question.id %}"> 
            {% csrf_token %}
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <td><input value="{{ question.option_1 }}" required id="option_1" name="answer" type="radio" /></td>
                    <th><label for="option_1">{{ question.option_1 }}</label></th>
                </tr>
                <tr>
                    <td><input value="{{ question.option_2 }}" required id="option_2" name="answer" type="radio" /></td>
                    <th><label for="option_2">{{ question.option_2 }}</label></th>
                </tr>
                <tr>
                    <td><input value="{{ question.option_3 }}" required id="option_3" name="answer" type="radio" /></td>
                    <th><label for="option_3">{{ question.option_3 }}</label></th>
                </tr>
                <tr>
                    <td><input value="{{ question.option_4 }}" required id="option_4" name="answer" type="radio" /></td>
                    <th><label for="option_4">{{ question.option_4 }}</label></th>
                </tr>
            </table>    
        </div> 
        <div class="card-footer">                       
            <input type="submit" name="submit" value="submit" class="btn btn-primary submitBtn" /> 
        </div>
        </form>
    </div>

<script type="text/javascript">
    // Всплывающее окно, если не выбрал ответ
    $(document).ready(function(){
        $(".submitBtn").on('click', function(){
            var _checkedAns=$("input[name='answer']:checked").val();
            if(_checkedAns==undefined){
                alert('Выбери один из ответов!');
                return false;
            }            
        });
    });
</script>

{% endblock %}

testapp/templates/main/home.html
{% extends 'base.html' %}
{% block title %}Главная страница{% endblock %} 
{% block content %}

<h3 class="my-3">Тесты Тут!!!</h3>

<div class="row">
    {% for category in catData %}
    <div class="col-md-4">
        <div class="card">
            <a href="{% url 'main:cat_question' category.id %}"><img src="{{ category.image.url }}" class="card-img-top" alt="{{ category.title }}" width="250" height="250"></a>
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'main:cat_question' category.id %}">{{ category.title }}</a></h5>                
                
              </div>        
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %} 

testapp/templates/main/result.html
{% extends 'base.html' %}
{% block title %}Вопросы Категории {{ category }}{% endblock %}
{% block content %}
    <h2 class="my-4">Результаты</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Категории</th>
            <th>Вопрос</th>
            <th>Правильный ответ</th>
            <th>Выбранный ответ</th>            
        </tr>
        </thead>
        <tbody>
            {% for row in result %}
            <tr>
                <td>{{ row.question.category }}</td>
                <td>{{ row.question }}</td>
                <td>{{ row.question.right_option }}</td>
                {% if row.question.right_option == row.right_answer %}
                <td class="bg-success text-white">{{ row.right_answer }}</td>
                {% else %}
                <td class="bg-danger text-white">{{ row.right_answer }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <h3 class="my-4">Подробная информация</h3>
    <table class="table table-bordered">
        <tr>
            <th>Общее кол-во вопросов</th>
            <td>{{ result.count }}</td>
        </tr>        
        <tr>
            <th>Кол-во правильных ответов</th>
            <td>{{ rightAnswer }}</td>
        </tr>
        <tr>
            <th>Процент правильных ответов</th>
            <td>{{ percentage }}%</td>
        </tr>
    </table>    

{% endblock %}

testapp/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

testapp/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>            
            <a href="{% url 'users:signup' %}" class="btn btn-link">
              Нет Учётной записи, Вам сюда?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

testapp/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}<title>Востановление пароля</title>{% endblock %}
{% block content %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'password_reset_form' %}">
              {% csrf_token %}              
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">                  
                  Отправить пароль 
                </button>
              </form>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

testapp/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}